### ISSUE TITLE
resources.ActiveFixture.start_date no minutes

### ISSUE THREAD

**Issue by liampauling** [betcode-org/betconnect#18]
Expected behaviour or can the time be added as well?

![Screenshot 2022-02-28 at 15 21 31](https://user-images.githubusercontent.com/12016537/156009009-17ab1bc6-8399-4feb-a052-9388670b1c29.png)

**Comment by varneyo** [comment]
Its expected I guess as a string date is returned which is parsed to a datetime rather than a date. Probably can tack on the time though. 

![image](https://user-images.githubusercontent.com/8698145/156010881-52860061-a04b-4af7-87a0-2217de319351.png

Something like this I think will work: 

  def date_parser(cls, v, values) -> datetime:
      if isinstance(v, str):
          return datetime.fromisoformat(f"{v} {values['time']}")
      elif isinstance(v, datetime):
          return v
      else:
          raise TypeError(f"Expected value of type str or datetime")

![image](https://user-images.githubusercontent.com/8698145/156011746-7e7f1ff9-70d1-4f7d-a871-c0a544d1f84d.png)

**Comment by liampauling** [comment]
Could keep `start_date` as it is and add a `start_datetime` property that uses the `data_parser` code?

**Comment by varneyo** [comment]
Something like this will work, time changed to time from str and a property. 

```python
class ActiveFixture(BaseResource):
    fixture_id: int
    display_name: str
    time: time
    each_way_active: Optional[str] = Field(default=None)
    start_date: datetime = Field(alias="startdate")

    # waiting on sport_id: int ?
    # waiting on region_id: int ?
    # waiting on competition_id: int ?

    @property
    def start_date_time(self)->datetime:
        return self.start_date.replace(hour=self.time.hour,minute=self.time.minute)

    # noinspection PyMethodParameters
    @validator("start_date", pre=True)
    def date_parser(cls, v) -> datetime:
        if isinstance(v, str):
            return datetime.fromisoformat(v)
        elif isinstance(v, datetime):
            return v
        else:
            raise TypeError(f"Expected value of type str or datetime")

    def __repr__(self) -> str:
        return f"Fixture: {self.display_name}({self.fixture_id}) {self.start_date}"
```
